services:
  prom-config-builder:
    build:
      context: .
      dockerfile: ./tools/python.Dockerfile
    volumes:
      - ./config/prometheus:/config/prometheus
      - ./tools/prom-config-builder/:/tools/prom-config-builder
    user: "${UID}:${GID}"

