services:
  prom-config-builder:
    build:
      context: .
      dockerfile: ./tools/prom-config-builder/prom-config-builder.Dockerfile
    volumes:
      - ./config/victoria-metrics:/config/victoria-metrics
      - ./tools/prom-config-builder/:/tools/prom-config-builder

