apiVersion: 1

datasources:
  - name: prometheus
    uid: prometheus 
    type: prometheus
    access: proxy
    url: http://$PROM_HOST:9090
    jsonData:
      httpMethod: POST
  - name: prometheus1d
    uid: prometheus1d 
    type: prometheus
    access: proxy
    url: http://$PROM_HOST:9090
    jsonData:
      httpMethod: POST
      timeInterval: "1d"

