apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: prometheus 
    type: prometheus
    access: proxy
    url: http://$PROM_HOST:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: "1d"