apiVersion: 1

datasources:
  - name: prometheus
    uid: prometheus 
    type: prometheus
    access: proxy
    url: http://$PROM_HOST:9090
    jsonData:
      httpMethod: POST
  - name: VictoriaMetrics1d
    uid: victoriametrics1d 
    type: prometheus
    access: proxy
    url: http://$PROM_HOST:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: "1d"
